// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function make(input) {
  switch (input) {
    case "(" :
        return 1;
    case ")" :
        return -1;
    default:
      return 0;
  }
}

var Level = {
  make: make
};

function make$1(input) {
  return input.split("").reduce((function (acc, curr) {
                return acc + make(curr) | 0;
              }), 0);
}

var PartOne = {
  make: make$1
};

function make$2(input) {
  return input.split("").reduce((function (param, curr, i) {
                  var isBasement = param[1];
                  var match = param[0] + make(curr) | 0;
                  if (isBasement !== undefined) {
                    return [
                            match,
                            isBasement
                          ];
                  } else if (match < 0) {
                    return [
                            match,
                            i + 1 | 0
                          ];
                  } else {
                    return [
                            match,
                            undefined
                          ];
                  }
                }), [
                0,
                undefined
              ])[1];
}

var PartTwo = {
  make: make$2
};

exports.Level = Level;
exports.PartOne = PartOne;
exports.PartTwo = PartTwo;
/* No side effect */
