[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
nom = "7.1.1"
itertools = "0.12.0"
regex = "1"
rayon = "1.8.0"
graphrs = "0.7.0"

[dev-dependencies]
rstest = "0.18.2"
