[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Rickard Natt och Dag <rickard@hey.com>"]
edition = "2018"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.9.0"
lazy_static = "1"
regex = "1"
anyhow = "1.0.34"
