[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
serial_test = "0.9.0"
pathfinding = "4.0.0"
nom = "7.1.1"
itertools = "0.10.1"
