// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var DayOne_test = 0;

var DayTwo_test = 0;

var DayFive_test = 0;

var DayFour_test = 0;

var DayThree_test = 0;

var GuardOne = 0;

var GuardTwo = 0;

var DayFourData = 0;

var HelpersFour = 0;

var DayTwoData = 0;

var InventoryOne = 0;

var InventoryTwo = 0;

var Alchemical = 0;

var DayFiveData = 0;

var DayOneData = 0;

var CalibrateOne = 0;

var CalibrateTwo = 0;

var SliceIt = 0;

var DayThreeData = 0;

var Utils = 0;

var Levenshtein = 0;

exports.DayOne_test = DayOne_test;
exports.DayTwo_test = DayTwo_test;
exports.DayFive_test = DayFive_test;
exports.DayFour_test = DayFour_test;
exports.DayThree_test = DayThree_test;
exports.GuardOne = GuardOne;
exports.GuardTwo = GuardTwo;
exports.DayFourData = DayFourData;
exports.HelpersFour = HelpersFour;
exports.DayTwoData = DayTwoData;
exports.InventoryOne = InventoryOne;
exports.InventoryTwo = InventoryTwo;
exports.Alchemical = Alchemical;
exports.DayFiveData = DayFiveData;
exports.DayOneData = DayOneData;
exports.CalibrateOne = CalibrateOne;
exports.CalibrateTwo = CalibrateTwo;
exports.SliceIt = SliceIt;
exports.DayThreeData = DayThreeData;
exports.Utils = Utils;
exports.Levenshtein = Levenshtein;
/* No side effect */
