// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Utils$AdventOfCode2018 = require("../utils/Utils.bs.js");
var HelpersFour$AdventOfCode2018 = require("./HelpersFour.bs.js");

function findSleepy(input) {
  var sleepyGuard = { };
  var laziestGuard = Belt_Array.get(Utils$AdventOfCode2018.sortInPlaceWith(HelpersFour$AdventOfCode2018.createList(input), (function (param, param$1) {
              return param$1[1][0] - param[1][0] | 0;
            })), 0);
  var match = laziestGuard !== undefined ? laziestGuard : /* tuple */[
      "0",
      /* tuple */[
        0,
        /* array */[]
      ]
    ];
  Belt_Array.forEach(HelpersFour$AdventOfCode2018.createInterval(match[1][1]), (function (time) {
          return HelpersFour$AdventOfCode2018.updateDictByOne(sleepyGuard, String(time));
        }));
  var match$1 = HelpersFour$AdventOfCode2018.getMostSleepy(sleepyGuard);
  if (match$1 !== undefined) {
    return Caml_int32.imul(Caml_format.caml_int_of_string(match$1[0]), Caml_format.caml_int_of_string(match[0]));
  } else {
    return 0;
  }
}

exports.findSleepy = findSleepy;
/* HelpersFour-AdventOfCode2018 Not a pure module */
