// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Utils$AdventOfCode2018 = require("../utils/Utils.bs.js");

function convertToNumbers(row) {
  if (row !== undefined) {
    return Belt_Array.map(row, (function (rowValue) {
                  return rowValue.length;
                }));
  } else {
    return /* array */[0];
  }
}

function sortAndMatch(row) {
  return Js_primitive.null_to_opt(row.sort().join("").match((/(.)\1+/g)));
}

function findDuplicateCharacters(input) {
  return Belt_Array.reduce(convertToNumbers(sortAndMatch(Belt_Array.reduce(Belt_Array.map(Belt_Array.map(Belt_Array.map(input, (function (row) {
                                        return sortAndMatch(row.split(""));
                                      })), convertToNumbers), Utils$AdventOfCode2018.removeDuplicates), /* array */[], Belt_Array.concat))), 1, Caml_int32.imul);
}

exports.convertToNumbers = convertToNumbers;
exports.sortAndMatch = sortAndMatch;
exports.findDuplicateCharacters = findDuplicateCharacters;
/* No side effect */
