// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Perf_hooks = require("perf_hooks");
var Day01Input$2020 = require("./Day01Input.bs.js");

function partOne(param) {
  var s = 0;
  for(var i = 0 ,i_finish = Day01Input$2020.data.length; i <= i_finish; ++i){
    var i$1 = Belt_Array.get(Day01Input$2020.data, i);
    if (i$1 !== undefined) {
      var v = 2020 - i$1 | 0;
      if (Day01Input$2020.data.includes(v)) {
        s = Math.imul(i$1, v);
      }
      
    }
    
  }
  return s;
}

function partTwo(param) {
  var s = 0;
  for(var i = 0 ,i_finish = Day01Input$2020.data.length; i <= i_finish; ++i){
    for(var j = 0 ,j_finish = Day01Input$2020.data.length; j <= j_finish; ++j){
      var v1 = Belt_Array.get(Day01Input$2020.data, i);
      var v2 = Belt_Array.get(Day01Input$2020.data, j);
      if (v1 !== undefined && v2 !== undefined && (v1 + v2 | 0) <= 2020) {
        var v = (2020 - v1 | 0) - v2 | 0;
        if (Day01Input$2020.data.includes(v)) {
          s = Math.imul(Math.imul(v1, v2), v);
        }
        
      }
      
    }
  }
  return s;
}

var t0 = Curry._1(Perf_hooks.performance.now, undefined);

console.log("Part 1");

console.log("Result: ", partOne(undefined));

var t1 = Curry._1(Perf_hooks.performance.now, undefined);

console.log("Time: ", (t1 - t0 | 0).toPrecision(2) + " ms");

var t0$1 = Curry._1(Perf_hooks.performance.now, undefined);

console.log("\nPart 2");

console.log("Result: ", partTwo(undefined));

var t1$1 = Curry._1(Perf_hooks.performance.now, undefined);

console.log("Time: ", (t1$1 - t0$1 | 0).toPrecision(2) + " ms");

exports.partOne = partOne;
exports.partTwo = partTwo;
exports.t0 = t0$1;
exports.t1 = t1$1;
/* t0 Not a pure module */
