// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.bs.js");
var Day1$AdventOfCode2019 = require("../src/day-1-not-quite-lisp/Day1.bs.js");
var Day1Data$AdventOfCode2019 = require("../src/day-1-not-quite-lisp/Day1Data.bs.js");

Jest.describe("PartOne", (function (param) {
        Jest.test("test first example input", (function (param) {
                return Jest.Expect.toEqual(0, Jest.Expect.expect(Day1$AdventOfCode2019.PartOne.make("(())")));
              }));
        Jest.test("test second example input", (function (param) {
                return Jest.Expect.toEqual(0, Jest.Expect.expect(Day1$AdventOfCode2019.PartOne.make("()()")));
              }));
        Jest.test("test second example input", (function (param) {
                return Jest.Expect.toEqual(3, Jest.Expect.expect(Day1$AdventOfCode2019.PartOne.make("))(((((")));
              }));
        return Jest.test("puzzle data", (function (param) {
                      return Jest.Expect.toEqual(232, Jest.Expect.expect(Day1$AdventOfCode2019.PartOne.make(Day1Data$AdventOfCode2019.data)));
                    }));
      }));

Jest.describe("PartTwo", (function (param) {
        Jest.test("test first example input", (function (param) {
                return Jest.Expect.toEqual(1, Jest.Expect.expect(Day1$AdventOfCode2019.PartTwo.make(")")));
              }));
        Jest.test("test second example input", (function (param) {
                return Jest.Expect.toEqual(5, Jest.Expect.expect(Day1$AdventOfCode2019.PartTwo.make("()())")));
              }));
        return Jest.test("puzzle data", (function (param) {
                      return Jest.Expect.toEqual(1783, Jest.Expect.expect(Day1$AdventOfCode2019.PartTwo.make(Day1Data$AdventOfCode2019.data)));
                    }));
      }));

/*  Not a pure module */
