// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var GuardOne$AdventOfCode2018 = require("../src/day-4-repose-record/GuardOne.bs.js");
var GuardTwo$AdventOfCode2018 = require("../src/day-4-repose-record/GuardTwo.bs.js");
var DayFourData$AdventOfCode2018 = require("../src/day-4-repose-record/DayFourData.bs.js");

var exampleDataOne = /* array */[
  "[1518-11-01 00:00] Guard #10 begins shift",
  "[1518-11-01 00:05] falls asleep",
  "[1518-11-01 00:25] wakes up",
  "[1518-11-02 00:50] wakes up",
  "[1518-11-01 00:30] falls asleep",
  "[1518-11-01 00:55] wakes up",
  "[1518-11-01 23:58] Guard #99 begins shift",
  "[1518-11-02 00:40] falls asleep",
  "[1518-11-03 00:29] wakes up",
  "[1518-11-03 00:05] Guard #10 begins shift",
  "[1518-11-03 00:24] falls asleep",
  "[1518-11-05 00:03] Guard #99 begins shift",
  "[1518-11-05 00:45] falls asleep",
  "[1518-11-04 00:36] falls asleep",
  "[1518-11-04 00:46] wakes up",
  "[1518-11-04 00:02] Guard #99 begins shift",
  "[1518-11-05 00:55] wakes up"
];

Jest.test("handles example input puzzle #1", (function (param) {
        return Jest.Expect[/* toEqual */12](240, Jest.Expect[/* expect */0](GuardOne$AdventOfCode2018.findSleepy(exampleDataOne)));
      }));

Jest.test("solves puzzle #1", (function (param) {
        return Jest.Expect[/* toEqual */12](19025, Jest.Expect[/* expect */0](GuardOne$AdventOfCode2018.findSleepy(DayFourData$AdventOfCode2018.data)));
      }));

Jest.test("handles example input puzzle #2", (function (param) {
        return Jest.Expect[/* toEqual */12](4455, Jest.Expect[/* expect */0](GuardTwo$AdventOfCode2018.findFrequentSleeper(exampleDataOne)));
      }));

Jest.test("solves puzzle #2", (function (param) {
        return Jest.Expect[/* toEqual */12](23776, Jest.Expect[/* expect */0](GuardTwo$AdventOfCode2018.findFrequentSleeper(DayFourData$AdventOfCode2018.data)));
      }));

exports.exampleDataOne = exampleDataOne;
/*  Not a pure module */
