// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Alchemical$AdventOfCode2018 = require("../src/day-5-alchemical-reduction/Alchemical.bs.js");

var exampleDataOne = "dabAcCaCBAcCcaDA";

Jest.test("handles example input puzzle #1", (function (param) {
        return Jest.Expect[/* toEqual */12](10, Jest.Expect[/* expect */0](Alchemical$AdventOfCode2018.polymerUnits(exampleDataOne)));
      }));

exports.exampleDataOne = exampleDataOne;
/*  Not a pure module */
