// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var DayTwoData$AdventOfCode2018 = require("../src/day-2-inventory-management-system/DayTwoData.bs.js");
var Levenshtein$AdventOfCode2018 = require("../src/utils/Levenshtein.bs.js");
var InventoryOne$AdventOfCode2018 = require("../src/day-2-inventory-management-system/InventoryOne.bs.js");
var InventoryTwo$AdventOfCode2018 = require("../src/day-2-inventory-management-system/InventoryTwo.bs.js");

var exampleDataOne = /* array */[
  "abcdef",
  "bababc",
  "abbcde",
  "abcccd",
  "aabcdd",
  "abcdee",
  "ababab"
];

Jest.test("handles example input puzzle #1", (function (param) {
        return Jest.Expect[/* toEqual */12](12, Jest.Expect[/* expect */0](InventoryOne$AdventOfCode2018.findDuplicateCharacters(exampleDataOne)));
      }));

Jest.test("solves puzzle #1", (function (param) {
        return Jest.Expect[/* toEqual */12](7163, Jest.Expect[/* expect */0](InventoryOne$AdventOfCode2018.findDuplicateCharacters(DayTwoData$AdventOfCode2018.data)));
      }));

var exampleDataTwo = /* array */[
  "abcde",
  "fghij",
  "klmno",
  "pqrst",
  "fguij",
  "axcye",
  "wvxyz"
];

Jest.test("levenshtein similarity", (function (param) {
        return Jest.Expect[/* toBeGreaterThan */5](0.8, Jest.Expect[/* expect */0](Levenshtein$AdventOfCode2018.similarity("bghfbsyxznoumkjleevacpwqtr", "bghfbtypznoumkjlxevacpwqtr")));
      }));

Jest.test("handles example input puzzle #2", (function (param) {
        return Jest.Expect[/* toEqual */12]("fgij", Jest.Expect[/* expect */0](InventoryTwo$AdventOfCode2018.findBoxes(exampleDataTwo)));
      }));

Jest.test("solves puzzle #2", (function (param) {
        return Jest.Expect[/* toEqual */12]("ighfbyijnoumxjlxevacpwqtr", Jest.Expect[/* expect */0](InventoryTwo$AdventOfCode2018.findBoxes(DayTwoData$AdventOfCode2018.data)));
      }));

exports.exampleDataOne = exampleDataOne;
exports.exampleDataTwo = exampleDataTwo;
/*  Not a pure module */
