// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var SliceIt$AdventOfCode2018 = require("../src/day-3-no-matter-how-you-slice-it/SliceIt.bs.js");
var DayThreeData$AdventOfCode2018 = require("../src/day-3-no-matter-how-you-slice-it/DayThreeData.bs.js");

var exampleDataOne = /* array */[
  "#1 @ 1,3: 4x4",
  "#2 @ 3,1: 4x4",
  "#3 @ 5,5: 2x2"
];

Jest.test("handles example input puzzle #1", (function (param) {
        return Jest.Expect[/* toEqual */12](4, Jest.Expect[/* expect */0](SliceIt$AdventOfCode2018.findOverlap(exampleDataOne)));
      }));

Jest.test("solves puzzle #1", (function (param) {
        return Jest.Expect[/* toEqual */12](100261, Jest.Expect[/* expect */0](SliceIt$AdventOfCode2018.findOverlap(DayThreeData$AdventOfCode2018.data)));
      }));

Jest.test("handles example input puzzle #2", (function (param) {
        return Jest.Expect[/* toEqual */12]("3", Jest.Expect[/* expect */0](SliceIt$AdventOfCode2018.findFabric(exampleDataOne)));
      }));

Jest.test("solves puzzle #2", (function (param) {
        return Jest.Expect[/* toEqual */12]("251", Jest.Expect[/* expect */0](SliceIt$AdventOfCode2018.findFabric(DayThreeData$AdventOfCode2018.data)));
      }));

exports.exampleDataOne = exampleDataOne;
/*  Not a pure module */
