name: Run tests

on:
  push:
    branches: 
      - master

jobs:
  javascript:
    name: Test JavaScript solutions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year: ['2022']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run tests
        run: |
          cd javascript/$YEAR
          npm ci
          npm test
        env:
          YEAR: ${{ matrix.year }}
          CI: true

  rescript:
    name: Test ReScript solutions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year: ['2015', '2018', '2019', '2020']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run tests
        run: |
          cd rescript/$YEAR
          npm ci
          npm run build
          npm test
        env:
          YEAR: ${{ matrix.year }}
          CI: true

  rust:
    name: Test Rust solutions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year: ['2015', '2016', '2019', '2020', '2021', '2022']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Rust (nightly)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
          override: true

      - name: Run linting
        run: |
          cd rust/$YEAR
          cargo clippy --all-targets --all-features -- -D warnings
        env:
          YEAR: ${{ matrix.year }}

      - name: Run tests
        run: |
          cd rust/$YEAR
          cargo test --locked
        env:
          YEAR: ${{ matrix.year }}

